/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.screens;


//Imports
import com.clases.Articulo;
import com.clases.SeccionTienda;
import com.clases.Talla;
import com.dao.ArticuloJpaController;
import com.dao.SeccionTiendaJpaController;
import com.dao.TallaJpaController;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRSaveContributor;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author david
 */
public class FmrArticulos extends javax.swing.JFrame {

    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    NombreEmpleado N = new NombreEmpleado();
    static Logs log = new Logs();
    ArticuloJpaController daoArticulo = new ArticuloJpaController();
    SeccionTiendaJpaController daoSeccionTienda = new SeccionTiendaJpaController();
    TallaJpaController daoTalla = new TallaJpaController();
    
    Articulo objArticulo = new Articulo();
    DecimalFormat formateador = new DecimalFormat("####.00");
    
    public FmrArticulos() {
        initComponents();
        this.setLocationRelativeTo(null);              
        //Icono
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        setIconImage(icon);
        ActualizarArticulo();
        listaSeccionTienda();
        listaTalla();
        Txt_Activo.setVisible(false);
        Btn_Editar.setEnabled(false);
        Btn_Activar_Desactivar.setEnabled(false);
        RestringirPermisos(ValidarAgregar(N.id),ValidarEditar(N.id),ValidarDesactivar(N.id),ValidarImprimir(N.id),ValidarBuscar(N.id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Articulo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_IdArticulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_NombreArticulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_DescripcionArticulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_PrecioArticulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Txt_StockMin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_StockAct = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Txt_StockMax = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        Txt_Activo = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        Btn_Imprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Btn_Añadir = new javax.swing.JButton();
        Btn_Editar = new javax.swing.JButton();
        Btn_Activar_Desactivar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Regresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Artículos - Microcosmos");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        Tbl_Articulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Descripción", "Stock Actual", "Stock Mínimo", "Stock Máximo", "Precio", "Talla", "Sección"
            }
        ));
        Tbl_Articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ArticuloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Articulo);
        if (Tbl_Articulo.getColumnModel().getColumnCount() > 0) {
            Tbl_Articulo.getColumnModel().getColumn(0).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(1).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(2).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(3).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(4).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(5).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(6).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(7).setResizable(false);
            Tbl_Articulo.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(49, 49, 49));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMicrocosmos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(60, 63, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 230));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 230));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresar Datos");
        jLabel5.setMaximumSize(new java.awt.Dimension(299, 41));
        jLabel5.setPreferredSize(new java.awt.Dimension(299, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID Artículo");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_IdArticulo.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre Artículo");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_NombreArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_NombreArticuloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_NombreArticuloKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Descripción");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_DescripcionArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DescripcionArticuloActionPerformed(evt);
            }
        });
        Txt_DescripcionArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DescripcionArticuloKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Precio Artículo");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_PrecioArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_PrecioArticuloKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Stock Mínimo");
        jLabel10.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_StockMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_StockMinKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Stock Actual");
        jLabel9.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_StockAct.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Stock Máximo");
        jLabel12.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel12.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_StockMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_StockMaxKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Sección");
        jLabel13.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Talla");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Talla" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Sección" }));

        Txt_Activo.setMinimumSize(new java.awt.Dimension(0, 0));
        Txt_Activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ActivoActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Btn_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresoraAzul.png"))); // NOI18N
        Btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Txt_PrecioArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Txt_NombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Buscar))
                            .addComponent(Txt_IdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                            .addComponent(Txt_DescripcionArticulo))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(Txt_Activo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_StockMin)
                    .addComponent(Txt_StockAct)
                    .addComponent(Txt_StockMax)
                    .addComponent(jComboBox2, 0, 150, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(Btn_Imprimir))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Imprimir)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_IdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_StockAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_NombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_StockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_PrecioArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_StockMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_DescripcionArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Activo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(60, 63, 65));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 130));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 130));

        Btn_Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        Btn_Añadir.setText("Añadir");
        Btn_Añadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Añadir.setFocusPainted(false);
        Btn_Añadir.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Añadir.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Añadir.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AñadirActionPerformed(evt);
            }
        });

        Btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actualizar2.png"))); // NOI18N
        Btn_Editar.setText("Actualizar");
        Btn_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Editar.setFocusPainted(false);
        Btn_Editar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Editar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Editar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });

        Btn_Activar_Desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AD.png"))); // NOI18N
        Btn_Activar_Desactivar.setText("Desactivar");
        Btn_Activar_Desactivar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Activar_Desactivar.setFocusPainted(false);
        Btn_Activar_Desactivar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Activar_Desactivar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Activar_Desactivar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Activar_Desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Activar_DesactivarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Limpiar.setFocusPainted(false);
        Btn_Limpiar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Limpiar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Limpiar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        Btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        Btn_Regresar.setText("Regresar");
        Btn_Regresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Regresar.setFocusPainted(false);
        Btn_Regresar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegresarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Acciones");
        jLabel11.setMaximumSize(new java.awt.Dimension(265, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(265, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(265, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Btn_Activar_Desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Activar_Desactivar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Regresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Añadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreArticuloKeyTyped

        char c = evt.getKeyChar();
        String Texto = Txt_NombreArticulo.getText();

        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')){

            if(c == 'á' || c == 'é' || c == 'í' || c == 'ó' || c == 'ú' || c == 47 || c == 32 || c == 45){
            }
            else{
             evt.consume();
            }

        }
      
        if (Txt_NombreArticulo.getText().length() >= 50){
        
        evt.consume();
        
        }
        
        
         if((evt.getKeyChar() == 22)){
        
            Txt_NombreArticulo.setText(Texto.substring(0, 50));
                    
        }
        
        if (Txt_NombreArticulo.getText().length() == 1){

            char mayuscula = Texto.charAt(0);
            Texto = Character.toUpperCase(mayuscula)+ Texto.substring(1,Texto.length());
            Txt_NombreArticulo.setText(Texto);

        }
         
    }//GEN-LAST:event_Txt_NombreArticuloKeyTyped

    private void Txt_ActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ActivoActionPerformed

    }//GEN-LAST:event_Txt_ActivoActionPerformed

    private void Btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegresarActionPerformed
         
        FmrMenú M = new FmrMenú();
        M.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_RegresarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        try{
        LimpiarArticulo();
        ActualizarArticulo();
        }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al limpiar: " + ex);
          
        }
        
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_Activar_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Activar_DesactivarActionPerformed
         
        int fila = Tbl_Articulo.getSelectedRow();

        if(fila != -1){
        try{
            Activar_Desactivar();
        }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al Desactivar: " + ex);
          
        }
        }else{

            JOptionPane.showMessageDialog(this, "Debe seleccionar el elemento a Activar o Desactivar en la Fila");

        }
        
    }//GEN-LAST:event_Btn_Activar_DesactivarActionPerformed

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
        
          int fila = Tbl_Articulo.getSelectedRow();
        if(fila == -1){

            JOptionPane.showMessageDialog(this, "Debe seleccionar el elemento a actualizar en la Fila");

        }else{

            try{
            EditarArticulo();

            }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al Actualizar: " + ex);
          
        }
            
        } 
        
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void Btn_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AñadirActionPerformed
         
        try {
          LlenarArticulo();
        } catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al llenar: " + ex);
          
        }
       
        
    }//GEN-LAST:event_Btn_AñadirActionPerformed

    private void Tbl_ArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ArticuloMouseClicked
        
        int fila =  Tbl_Articulo.getSelectedRow();
        
        if(ValidarEditar(N.id) == true || ValidarDesactivar(N.id) == true){
        if(fila == -1){
        
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");
        
        }else{
            
        Btn_Añadir.setEnabled(false);
        if(ValidarEditar(N.id) == true && ValidarDesactivar(N.id) == false){
        Btn_Editar.setEnabled(true);
        Btn_Activar_Desactivar.setEnabled(false);
        }
        if(ValidarEditar(N.id) == false && ValidarDesactivar(N.id) == true){
        Btn_Editar.setEnabled(false);
        Btn_Activar_Desactivar.setEnabled(true);
        }
        if(ValidarEditar(N.id) == true && ValidarDesactivar(N.id) == true){
        Btn_Editar.setEnabled(true);
        Btn_Activar_Desactivar.setEnabled(true);
        }
        String Id = Tbl_Articulo.getValueAt(fila, 0).toString();
        String Nombre = Tbl_Articulo.getValueAt(fila, 1).toString();
        String Talla = Tbl_Articulo.getValueAt(fila, 2).toString();
        String Precio = Tbl_Articulo.getValueAt(fila, 3).toString();
        String SecciónTienda = Tbl_Articulo.getValueAt(fila, 4).toString();
        String StockActual = Tbl_Articulo.getValueAt(fila, 5).toString();
        String StockMínimo = Tbl_Articulo.getValueAt(fila, 6).toString();
        String StockMáximo = Tbl_Articulo.getValueAt(fila, 7).toString();
        String Descripcion = Tbl_Articulo.getValueAt(fila, 8).toString();
        String Activo = Tbl_Articulo.getValueAt(fila, 9).toString();
        
        

        Txt_IdArticulo.setText(Id);
        Txt_NombreArticulo.setText(Nombre);
        jComboBox1.setSelectedItem(Talla);
        Txt_PrecioArticulo.setText(Precio);
        jComboBox2.setSelectedItem(SecciónTienda);
        Txt_StockAct.setText(StockActual);
        Txt_StockMin.setText(StockMínimo);
        Txt_StockMax.setText(StockMáximo);
        Txt_DescripcionArticulo.setText(Descripcion);
        Txt_Activo.setText(Activo);
        
        if(Activo == "Activado"){
        Btn_Activar_Desactivar.setText("Desactivar");
        }else{
        
             Btn_Activar_Desactivar.setText("Activar");
        
        }
        }        
        }
    }//GEN-LAST:event_Tbl_ArticuloMouseClicked

    private void Txt_NombreArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreArticuloKeyReleased

        
    }//GEN-LAST:event_Txt_NombreArticuloKeyReleased

    private void Txt_PrecioArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_PrecioArticuloKeyTyped
         
        char c = evt.getKeyChar();
        String Texto = Txt_PrecioArticulo.getText();
        
        if(c < '0' || c > '9') {

            if(c == 46){
            }
            else{
            evt.consume();
            }
             
        }
        
         if (Txt_PrecioArticulo.getText().length() >= 8){
        
        evt.consume();
        
        }
        
        if((evt.getKeyChar() == 22)){
        
            Txt_PrecioArticulo.setText(Texto.substring(0, 8));
                    
        }
        
        
        
    }//GEN-LAST:event_Txt_PrecioArticuloKeyTyped

    private void Txt_DescripcionArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DescripcionArticuloKeyTyped
       
           char c = evt.getKeyChar();
        String Texto = Txt_DescripcionArticulo.getText();
        
        
        if((evt.getKeyChar() == 22)){
        
            Txt_DescripcionArticulo.setText(Texto.substring(0, 50));
                    
        }
        
        if (Txt_DescripcionArticulo.getText().length() >= 50){
        
        evt.consume();
        
        }
        
        if (Txt_DescripcionArticulo.getText().length() == 1){

            char mayuscula = Texto.charAt(0);
            Texto = Character.toUpperCase(mayuscula)+ Texto.substring(1,Texto.length());
            Txt_DescripcionArticulo.setText(Texto);

        }
        
    }//GEN-LAST:event_Txt_DescripcionArticuloKeyTyped

    private void Txt_StockMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_StockMinKeyTyped
         
        char c = evt.getKeyChar();
        String Texto = Txt_StockMin.getText();
       
        if(c < '0' || c > '9') {
        
            evt.consume();
                    
        }
        
        if((evt.getKeyChar() == 22)){
        
            Txt_StockMin.setText(Texto.substring(0, 5));
                    
        }
        
        if (Txt_StockMin.getText().length() >= 5){
        
        evt.consume();
        
        }
        
        
    }//GEN-LAST:event_Txt_StockMinKeyTyped

    private void Txt_StockMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_StockMaxKeyTyped
         
        char c = evt.getKeyChar();
        String Texto = Txt_StockMax.getText();
       
        if(c < '0' || c > '9') {
        
            evt.consume();
                    
        }
        
        if((evt.getKeyChar() == 22)){
        
            Txt_StockMax.setText(Texto.substring(0, 5));
                    
        }
        
        if (Txt_StockMax.getText().length() >= 5){
        
        evt.consume();
        
        }
        
        
    }//GEN-LAST:event_Txt_StockMaxKeyTyped

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

       try{        
           
        ActualizarArticulo2(Txt_NombreArticulo.getText());
        
       }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al buscar: " + ex);
          
        }
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void Txt_DescripcionArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DescripcionArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DescripcionArticuloActionPerformed

    private void Btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ImprimirActionPerformed

        try{
        GenerarReporte();
        }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al imprimir reporte: " + ex);
          
        }
    }//GEN-LAST:event_Btn_ImprimirActionPerformed

     private void LimpiarArticulo(){
     
        try{
            
        if(ValidarAgregar(N.id) == true){
        Btn_Añadir.setEnabled(true);
        }
        Btn_Editar.setEnabled(false);
        Btn_Activar_Desactivar.setEnabled(false);
        Txt_IdArticulo.setText("");
        Txt_NombreArticulo.setText("");
        Txt_PrecioArticulo.setText("");
        Txt_DescripcionArticulo.setText("");
        jComboBox1.setSelectedIndex(0);
        Txt_StockAct.setText("");
        Txt_StockMin.setText("");
        Txt_StockMax.setText("");
        jComboBox2.setSelectedIndex(0);
        
        }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al limpiar: " + ex);
          
        }
        
     
     }
    
    
     private void ActualizarArticulo(){
       
            DefaultTableModel t = new DefaultTableModel();
            Tbl_Articulo.setModel(t);
            t.addColumn("Id");
            t.addColumn("Artículo");
            t.addColumn("Talla");
            t.addColumn("Precio");
            t.addColumn("Sección Tienda");
            t.addColumn("Stock Actual");
            t.addColumn("Stock Mínimo");
            t.addColumn("Stock Máximo");
            t.addColumn("Descripcion");
            t.addColumn("Estado");
        
            List<Articulo> articulo = this.daoArticulo.findArticuloEntities();
        
            String s;
            for(Articulo Articulo : articulo){
                
                if(Articulo.isActivoArticulo() == true){
                s = "Activado";
                }else{
                s = "Desactivado";
                }
                t.addRow(
                    new Object[]{
                        Articulo.getIdArticulo(),
                        Articulo.getNombreArticulo(),
                        GetNombreTalla(Articulo.getIdTalla()),
                        formateador.format(Articulo.getPrecioArticulo()),
                        GetNombreSeccionTienda(Articulo.getIdSeccionTienda()),
                        Articulo.getStock(),
                        Articulo.getStockMinimo(),
                        Articulo.getStockMaximo(),
                        Articulo.getDescripcionArticulo(),
                        s
                    });
            }
       
       
       }
    
     
     private void Activar_Desactivar(){
        
        int fila = Tbl_Articulo.getSelectedRow();
        
        String a = Txt_Activo.getText().toString();
       
        if(a.equals("Activado")){
                    
            
            objArticulo.setIdArticulo(Integer.parseInt(Txt_IdArticulo.getText()));
            objArticulo.setNombreArticulo(Tbl_Articulo.getValueAt(fila, 1).toString());
            objArticulo.setIdTalla(GetIdTalla(Tbl_Articulo.getValueAt(fila, 2).toString()));
            objArticulo.setPrecioArticulo(Double.parseDouble(Tbl_Articulo.getValueAt(fila, 3).toString()));
            objArticulo.setIdSeccionTienda(GetIdSeccionTienda(Tbl_Articulo.getValueAt(fila, 4).toString()));
            objArticulo.setStock(Integer.parseInt(Tbl_Articulo.getValueAt(fila, 5).toString()));
            objArticulo.setStockMinimo(Integer.parseInt(Tbl_Articulo.getValueAt(fila, 6).toString()));
            objArticulo.setStockMaximo(Integer.parseInt(Tbl_Articulo.getValueAt(fila, 7).toString()));
            objArticulo.setDescripcionArticulo(Tbl_Articulo.getValueAt(fila, 8).toString());
            objArticulo.setActivoArticulo(false);
                    
        
        try {
            daoArticulo.edit(objArticulo);
            ActualizarArticulo();
            Btn_Activar_Desactivar.setText("Activar");
            JOptionPane.showMessageDialog(this, "Se desactivó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al desactivar: " + ex);
          
        }
        
        
        LimpiarArticulo();
        
        }else{
        
            objArticulo.setIdArticulo(Integer.parseInt(Txt_IdArticulo.getText()));
            objArticulo.setNombreArticulo(Tbl_Articulo.getValueAt(fila, 1).toString());
            objArticulo.setIdTalla(GetIdTalla(Tbl_Articulo.getValueAt(fila, 2).toString()));
            objArticulo.setPrecioArticulo(Double.parseDouble(Tbl_Articulo.getValueAt(fila, 3).toString()));
            objArticulo.setIdSeccionTienda(GetIdSeccionTienda(Tbl_Articulo.getValueAt(fila, 4).toString()));
            objArticulo.setStock(Integer.parseInt(Tbl_Articulo.getValueAt(fila, 5).toString()));
            objArticulo.setStockMinimo(Integer.parseInt(Tbl_Articulo.getValueAt(fila, 6).toString()));
            objArticulo.setStockMaximo(Integer.parseInt(Tbl_Articulo.getValueAt(fila, 7).toString()));
            objArticulo.setDescripcionArticulo(Tbl_Articulo.getValueAt(fila, 8).toString());
            objArticulo.setActivoArticulo(true);
        
        try {
            daoArticulo.edit(objArticulo);
            ActualizarArticulo();
            Btn_Activar_Desactivar.setText("Desactivar");
            JOptionPane.showMessageDialog(this, "Se activó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al activar: " + ex);
          
        }
        
        LimpiarArticulo();
        
        }
        
        }
    
     private void LlenarArticulo(){
        
        if(Txt_NombreArticulo.getText().length() < 4){
        
        JOptionPane.showMessageDialog(this, "El nombre tiene que contener al menos 4 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_NombreArticulo.getText())== false){
        
        JOptionPane.showMessageDialog(this, "El nombre del articulo no puede contener 3 letras seguidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionDeRepetidos(Txt_NombreArticulo.getText())== true){
        
        JOptionPane.showMessageDialog(this, "No puede existir 2 articulos con el mismo nombre","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionDecimales(Txt_PrecioArticulo.getText())== false){
        
        JOptionPane.showMessageDialog(this, "El rango del precio está entre 10.00 - 99999.99","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_DescripcionArticulo.getText().length() < 8){
        
        JOptionPane.showMessageDialog(this, "La descripción tiene que contener al menos 8 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_DescripcionArticulo.getText())== false){
        
        JOptionPane.showMessageDialog(this, "La descripción no puede tener palabras con 3 letras repetidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox1.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una talla","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_StockMin.getText().length() < 1){
        
        JOptionPane.showMessageDialog(this, "El stock mínimo debe de contener por lo menos un digíto","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_StockMax.getText().length() < 1){
        
        JOptionPane.showMessageDialog(this, "El stock máximo debe de contener por lo menos un digíto","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Integer.parseInt(Txt_StockMin.getText()) >= Integer.parseInt(Txt_StockMax.getText()) ){
        
        JOptionPane.showMessageDialog(this, "El stock mínimo no puede ser mayor o igual al stock máximo","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox2.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una sección de la tienda","Error",JOptionPane.ERROR_MESSAGE);
        
        }else{
         
            objArticulo.setIdArticulo(IdArticulo());
            objArticulo.setNombreArticulo(Txt_NombreArticulo.getText());
            objArticulo.setPrecioArticulo(Double.parseDouble(Txt_PrecioArticulo.getText()));
            objArticulo.setDescripcionArticulo(Txt_DescripcionArticulo.getText());
            objArticulo.setIdTalla(GetIdTalla(String.valueOf(jComboBox1.getSelectedItem())));
            objArticulo.setStock(0);
            objArticulo.setStockMinimo(Integer.parseInt(Txt_StockMin.getText()));
            objArticulo.setStockMaximo(Integer.parseInt(Txt_StockMax.getText()));
            objArticulo.setIdSeccionTienda(GetIdSeccionTienda(String.valueOf(jComboBox2.getSelectedItem()))); 
            objArticulo.setActivoArticulo(true);
            
            
        try {
            daoArticulo.create(objArticulo);
            ActualizarArticulo();
            LimpiarArticulo();
            JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al llenar: " + ex);
          
        }
       }   
       } 
     
     
      private void EditarArticulo(){
            
        if(Txt_NombreArticulo.getText().length() < 4){
        
        JOptionPane.showMessageDialog(this, "El nombre tiene que contener al menos 4 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_NombreArticulo.getText())== false){
        
        JOptionPane.showMessageDialog(this, "El nombre del articulo no puede contener 3 letras seguidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionDecimales(Txt_PrecioArticulo.getText())== false){
        
        JOptionPane.showMessageDialog(this, "El rango del precio está entre 10.00 - 99999.99","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_DescripcionArticulo.getText().length() < 8){
        
        JOptionPane.showMessageDialog(this, "La descripción tiene que contener al menos 8 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_DescripcionArticulo.getText())== false){
        
        JOptionPane.showMessageDialog(this, "La descripción no puede tener palabras con 3 letras repetidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox1.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una talla","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_StockMin.getText().length() < 1){
        
        JOptionPane.showMessageDialog(this, "El stock mínimo debe de contener por lo menos un digíto","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_StockMin.getText().length() >= Txt_StockMax.getText().length() ){
        
        JOptionPane.showMessageDialog(this, "El stock mínimo no puede ser mayor o igual al stock máximo","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_StockMax.getText().length() < 1){
        
        JOptionPane.showMessageDialog(this, "El stock máximo debe de contener por lo menos un digíto","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox2.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una sección de la tienda","Error",JOptionPane.ERROR_MESSAGE);
        
        }else{
         
            objArticulo.setIdArticulo(Integer.parseInt(Txt_IdArticulo.getText()));
            objArticulo.setNombreArticulo(Txt_NombreArticulo.getText());
            objArticulo.setPrecioArticulo(Double.parseDouble(Txt_PrecioArticulo.getText()));
            objArticulo.setDescripcionArticulo(Txt_DescripcionArticulo.getText());
            objArticulo.setIdTalla(GetIdTalla(String.valueOf(jComboBox1.getSelectedItem())));
            objArticulo.setStock(Integer.parseInt(Txt_StockAct.getText()));
            objArticulo.setStockMinimo(Integer.parseInt(Txt_StockMin.getText()));
            objArticulo.setStockMaximo(Integer.parseInt(Txt_StockMax.getText()));
            objArticulo.setIdSeccionTienda(GetIdSeccionTienda(String.valueOf(jComboBox2.getSelectedItem()))); 
            
            String a = Txt_Activo.getText().toString();
            if(a.equals("Activado")){
            objArticulo.setActivoArticulo(true);
            }else{
            objArticulo.setActivoArticulo(false);
            }
            
        try {
            daoArticulo.edit(objArticulo);
            ActualizarArticulo();
            LimpiarArticulo();
             JOptionPane.showMessageDialog(this, "Se actualizó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al editar: " + ex);
          
        }
       }  
            
            }
          
     
    
          private static String GetNombreTalla(int id){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT nombreTalla FROM Talla WHERE idTalla = '"+ id+ "'";
              Query query = em.createQuery(select);
    
              return query.getSingleResult().toString() ;
            
          }         
   
          private static int GetIdTalla(String Nombre){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT idTalla FROM Talla WHERE nombreTalla = '"+ Nombre+ "'";
              Query query = em.createQuery(select);
    
              return Integer.parseInt(query.getSingleResult().toString());
            
          }   
          
          
          private static String GetNombreSeccionTienda(int id){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT nombreSeccionTienda FROM SeccionTienda WHERE idSeccionTienda = '"+ id+ "'";
              Query query = em.createQuery(select);
    
              return query.getSingleResult().toString() ;
            
          }   
          
          private static int GetIdSeccionTienda(String Nombre){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT idSeccionTienda FROM SeccionTienda WHERE nombreSeccionTienda = '"+ Nombre + "'";
              Query query = em.createQuery(select);
    
              return Integer.parseInt(query.getSingleResult().toString());
            
          }   
          
           public static int IdArticulo(){
        
             EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
             EntityManager em = emf.createEntityManager();
      
             String select = "SELECT Max(idArticulo)+1 FROM Articulo";
   
             Query query = em.createQuery(select);
        
              if(query.getSingleResult() == null){
             
             return 1;
             
             }else{
                 
             return Integer.parseInt(query.getSingleResult().toString());
             
             }
        
        }
          
        public void listaTalla(){
  
         jComboBox1.removeAllItems();
  
         List<Talla> talla = this.daoTalla.findTallaEntities();
  
         jComboBox1.addItem("Seleccione");
      
         for(Talla Talla : talla){
             
             if(Talla.isActivoTalla() == true){
             
             String lista = Talla.getNombreTalla();
             jComboBox1.addItem(lista);
             
             }              
                    }
  } 
    
    
    public void listaSeccionTienda(){
  
         jComboBox2.removeAllItems();
  
         List<SeccionTienda> seccionTienda = this.daoSeccionTienda.findSeccionTiendaEntities();
  
         jComboBox2.addItem("Seleccione");
      
         for(SeccionTienda SeccionTienda : seccionTienda){
             
             if(SeccionTienda.isActivoSeccionTienda() == true){
             String lista = SeccionTienda.getNombreSeccionTienda();
             jComboBox2.addItem(lista);
             }              
                    }
  }  
    
    
    public static boolean ValidacionDecimales(String Decimal){
        
        return Decimal.matches("^[1-9]{1}[0-9]{1,4}+\\.[0-9]{2}$");
                
        }
    
    
    
           public static boolean ValidacionDeRepetidos(String Nombre){
       
         EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
         EntityManager em = emf.createEntityManager();
      
             String select = "SELECT idArticulo FROM Articulo WHERE nombreArticulo  = '"+Nombre+ "'";
   
             Query query = em.createQuery(select);
       
             if(query.getResultList().size() == 0){
             
             return false;
             
             }else{
             
             return true;
                
             }
             
        }
        
        private static boolean ValidacionTresLetras(String cadena){
        
        String patron = "^(\\d|(([A-Za-zñÑáéíóúÁÉÍÓÚ\\s])\\3?(?!\\3)))+$";
        Pattern patt = Pattern.compile(patron);
        Matcher comparador = patt.matcher(cadena);
        
        if (!comparador.matches()) {
            
            return false;
            
        } else {
            
            return true;
        }
    
    
              
        }
    
    
    private void ActualizarArticulo2(String Nombres){
       
           DefaultTableModel t = new DefaultTableModel();
            Tbl_Articulo.setModel(t);
            t.addColumn("Id");
            t.addColumn("Artículo");
            t.addColumn("Talla");
            t.addColumn("Precio");
            t.addColumn("Sección Tienda");
            t.addColumn("Stock Actual");
            t.addColumn("Stock Mínimo");
            t.addColumn("Stock Máximo");
            t.addColumn("Descripcion");
            t.addColumn("Estado");
            
             List<Articulo> articulo  =  buscarArticulo(Nombres);
        
            String s;
            for(Articulo Articulo : articulo){
                
                if(Articulo.isActivoArticulo() == true){
                s = "Activado";
                }else{
                s = "Desactivado";
                }
                t.addRow(
                    new Object[]{
                        Articulo.getIdArticulo(),
                        Articulo.getNombreArticulo(),
                        GetNombreTalla(Articulo.getIdTalla()),
                        Articulo.getPrecioArticulo(),
                        GetNombreSeccionTienda(Articulo.getIdSeccionTienda()),
                        Articulo.getStock(),
                        Articulo.getStockMinimo(),
                        Articulo.getStockMaximo(),
                        Articulo.getDescripcionArticulo(),
                        s
                    });
            }
             
       }
       
       public List<Articulo> buscarArticulo(String Nombres){
       
           Articulo a;
             
           EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
           EntityManager em = emf.createEntityManager();
           String select = "SELECT a From Articulo a WHERE a.nombreArticulo LIKE'"+ Nombres + "%'";
           Query query = em.createQuery(select);
           List<Articulo> lista = query.getResultList();
           return lista;
           
       }
    
    
       private void GenerarReporte(){
       
        
             Connection con;
             
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            
        try{
        
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Microcosmos?zeroDateTimeBehavior=convertToNull", "root", "12345");
        
        JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/ReporteArticulos.jasper"));
        
        Map parametros = new HashMap<String, Object>();
        
        parametros.put("Empleado", N.getNombre());
   
        JasperPrint jprint = JasperFillManager.fillReport(report,parametros, con );
        JasperViewer view = new JasperViewer(jprint,false);
        view.setTitle("Reporte Articulos");
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        view.setIconImage(icon);
        

        final JRViewer viewer = new JRViewer(jprint);
            JRSaveContributor[] contrbs = viewer.getSaveContributors();

            for (JRSaveContributor saveContributor : contrbs)
            {
                if (!(saveContributor instanceof net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor
                    || saveContributor instanceof net.sf.jasperreports.view.save.JRPdfSaveContributor))
            viewer.removeSaveContributor(saveContributor);
        }
        view.setContentPane(viewer);
        view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        view.setVisible(true);
        

        view.show();

      
    }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al imprimir reporte: " + ex);
          
        }
        }catch(Exception ex){
        
        log.Logs("PantallaArticulos", "Error al imprimir reporte: " + ex);
          
        }
                
          }
       
       
    public void RestringirPermisos(boolean Agregar,boolean Editar,boolean Desactivar,boolean Imprimir,boolean buscar){
        
      
      if(Agregar == false){
       
        Btn_Añadir.setEnabled(false);
          
    }
      if(Editar == false){
          
        Btn_Editar.setEnabled(false);
                
    }
      if(Desactivar == false){

        Btn_Activar_Desactivar.setEnabled(false);
                
    }
      if(Imprimir == false){
          
        Btn_Imprimir.setEnabled(false);
                
    }
      if(buscar == false){
          
        Buscar.setEnabled(false);
                
    }
     
    }
          
          
    public boolean ValidarAgregar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where agregarArticulos = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
          
    public boolean ValidarEditar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where editarArticulos = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
    
    public boolean ValidarDesactivar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where desactivarArticulos = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
    
    public boolean ValidarImprimir(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where imprimirArticulos = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
    
    public boolean ValidarBuscar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where buscarArticulos = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
       
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Activar_Desactivar;
    private javax.swing.JButton Btn_Añadir;
    private javax.swing.JButton Btn_Editar;
    private javax.swing.JButton Btn_Imprimir;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Regresar;
    private javax.swing.JButton Buscar;
    private javax.swing.JTable Tbl_Articulo;
    private javax.swing.JTextField Txt_Activo;
    private javax.swing.JTextField Txt_DescripcionArticulo;
    private javax.swing.JTextField Txt_IdArticulo;
    private javax.swing.JTextField Txt_NombreArticulo;
    private javax.swing.JTextField Txt_PrecioArticulo;
    private javax.swing.JTextField Txt_StockAct;
    private javax.swing.JTextField Txt_StockMax;
    private javax.swing.JTextField Txt_StockMin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    
    
}
