/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.screens;

import com.clases.AreaLaboral;
import com.clases.Empleados;
import com.clases.Sexo;
import com.clases.TipoDocumento;
import com.dao.AreaLaboralJpaController;
import com.dao.EmpleadosJpaController;
import com.dao.SexoJpaController;
import com.dao.TipoDocumentoJpaController;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRSaveContributor;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author david
 */
public class FmrEmpleados extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    
    TipoDocumentoJpaController daoTipoDocumento = new TipoDocumentoJpaController();
    SexoJpaController daoSexo = new SexoJpaController();
    AreaLaboralJpaController daoAreaLaboral = new AreaLaboralJpaController();
    EmpleadosJpaController daoEmpleado = new EmpleadosJpaController();
    static Logs log = new Logs();
    Empleados objEmpleado = new Empleados();
    NombreEmpleado N = new NombreEmpleado();
    
    public FmrEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        setIconImage(icon);
        listaTipoDocumento();
        listaSexo();
        listaAreaLaboral();
        ActualizarEmpleados();
        Txt_Activo.setVisible(false);
        Btn_Editar.setEnabled(false);
        Btn_Activar_Desactivar.setEnabled(false);
        RestringirPermisos(ValidarAgregar(N.id),ValidarEditar(N.id),ValidarDesactivar(N.id),ValidarImprimir(N.id),ValidarBuscar(N.id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Empleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_IdEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_NombreEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_ApellidoEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_TelefonoEmpleado = new javax.swing.JTextField();
        Txt_CorreoEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Txt_DocumentoEmpleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Txt_Activo = new javax.swing.JTextField();
        Txt_FechaNacimiento = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        BuscarApellido = new javax.swing.JButton();
        Btn_Reporte = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Btn_Añadir = new javax.swing.JButton();
        Btn_Editar = new javax.swing.JButton();
        Btn_Activar_Desactivar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Regresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados - Microcosmos");
        setBackground(new java.awt.Color(60, 63, 65));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        Tbl_Empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Teléfono", "Dirección", "Correo", "TipoDocumento", "Documento", "Fecha", "Género", "Área", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_EmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Empleados);
        if (Tbl_Empleados.getColumnModel().getColumnCount() > 0) {
            Tbl_Empleados.getColumnModel().getColumn(0).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(1).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(2).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(3).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(4).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(5).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(6).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(7).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(8).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(9).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(10).setResizable(false);
            Tbl_Empleados.getColumnModel().getColumn(11).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(49, 49, 49));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 100));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoMicrocosmos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(60, 63, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 230));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 230));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresar Datos");
        jLabel5.setMaximumSize(new java.awt.Dimension(299, 41));
        jLabel5.setPreferredSize(new java.awt.Dimension(299, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID Empleado");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_IdEmpleado.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_NombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_NombreEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_NombreEmpleadoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_ApellidoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ApellidoEmpleadoActionPerformed(evt);
            }
        });
        Txt_ApellidoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_ApellidoEmpleadoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_TelefonoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_TelefonoEmpleadoKeyTyped(evt);
            }
        });

        Txt_CorreoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_CorreoEmpleadoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("E-mail");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo Documento");
        jLabel9.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Documento");
        jLabel10.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Fecha de Nacimiento");
        jLabel12.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel12.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(120, 20));

        Txt_DocumentoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DocumentoEmpleadoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Género");
        jLabel13.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel13.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(120, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Área Laboral");
        jLabel14.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel14.setMinimumSize(new java.awt.Dimension(120, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(120, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        Txt_FechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_FechaNacimientoKeyTyped(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        BuscarApellido.setText("Buscar");
        BuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarApellidoActionPerformed(evt);
            }
        });

        Btn_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresoraAzul.png"))); // NOI18N
        Btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Txt_Activo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_NombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(Txt_IdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_ApellidoEmpleado)
                            .addComponent(Txt_CorreoEmpleado)
                            .addComponent(Txt_TelefonoEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buscar)
                            .addComponent(BuscarApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                            .addComponent(Txt_DocumentoEmpleado)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txt_FechaNacimiento))
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(Btn_Reporte))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_Reporte)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_IdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_NombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_DocumentoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_ApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_TelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_CorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(Txt_Activo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(60, 63, 65));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 130));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 130));

        Btn_Añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        Btn_Añadir.setText("Añadir");
        Btn_Añadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Añadir.setFocusPainted(false);
        Btn_Añadir.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Añadir.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Añadir.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AñadirActionPerformed(evt);
            }
        });

        Btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actualizar2.png"))); // NOI18N
        Btn_Editar.setText("Actualizar");
        Btn_Editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Editar.setFocusPainted(false);
        Btn_Editar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Editar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Editar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });

        Btn_Activar_Desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AD.png"))); // NOI18N
        Btn_Activar_Desactivar.setText("Desactivar");
        Btn_Activar_Desactivar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Activar_Desactivar.setFocusPainted(false);
        Btn_Activar_Desactivar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Activar_Desactivar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Activar_Desactivar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Activar_Desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Activar_DesactivarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Limpiar.setFocusPainted(false);
        Btn_Limpiar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Limpiar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Limpiar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        Btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return.png"))); // NOI18N
        Btn_Regresar.setText("Regresar");
        Btn_Regresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Btn_Regresar.setFocusPainted(false);
        Btn_Regresar.setMaximumSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.setMinimumSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.setPreferredSize(new java.awt.Dimension(120, 50));
        Btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegresarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Acciones");
        jLabel11.setMaximumSize(new java.awt.Dimension(265, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(265, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(265, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Btn_Activar_Desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Activar_Desactivar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Regresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Añadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreEmpleadoKeyTyped

        char c = evt.getKeyChar();
        String Texto = Txt_NombreEmpleado.getText();

        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')){

            if(c == 'á' || c == 'é' || c == 'í' || c == 'ó' || c == 'ú'){
            }
            else{
            evt.consume();
            }

        }

         if (Txt_NombreEmpleado.getText().length() >= 20){
        
        evt.consume();
        
        }
    
         if((evt.getKeyChar() == 22)){
        
            Txt_NombreEmpleado.setText(Texto.substring(0, 20));
                    
        }
         
        
        if (Txt_NombreEmpleado.getText().length() == 1){

            char mayuscula = Texto.charAt(0);
            Texto = Character.toUpperCase(mayuscula)+ Texto.substring(1,Texto.length());
            Txt_NombreEmpleado.setText(Texto);

        }
    }//GEN-LAST:event_Txt_NombreEmpleadoKeyTyped

    private void Btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegresarActionPerformed
         
        FmrMenú M = new FmrMenú();
        M.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Btn_RegresarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed

        try{
        LimpiarEmpleados();
        ActualizarEmpleados();
        }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al limpiar: " + ex);
          
        }
        
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Tbl_EmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_EmpleadosMouseClicked
        
        int fila =  Tbl_Empleados.getSelectedRow();
        
        if(ValidarEditar(N.id) == true || ValidarDesactivar(N.id) == true){
        if(fila == -1){
        
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Fila");
        
                       
        }else{
            
        Btn_Añadir.setEnabled(false);
        
        if(ValidarEditar(N.id) == true && ValidarDesactivar(N.id) == false){
        Btn_Editar.setEnabled(true);
        Btn_Activar_Desactivar.setEnabled(false);
        }
        if(ValidarEditar(N.id) == false && ValidarDesactivar(N.id) == true){
        Btn_Editar.setEnabled(false);
        Btn_Activar_Desactivar.setEnabled(true);
        }
        if(ValidarEditar(N.id) == true && ValidarDesactivar(N.id) == true){
        Btn_Editar.setEnabled(true);
        Btn_Activar_Desactivar.setEnabled(true);
        }
        String Id = Tbl_Empleados.getValueAt(fila, 0).toString();
        String Nombre = Tbl_Empleados.getValueAt(fila, 1).toString();
        String Apellido = Tbl_Empleados.getValueAt(fila, 2).toString();
        String Telefono = Tbl_Empleados.getValueAt(fila, 3).toString();
        String Correo = Tbl_Empleados.getValueAt(fila, 4).toString();
        String TipoDocumento = Tbl_Empleados.getValueAt(fila, 5).toString();
        String Documento = Tbl_Empleados.getValueAt(fila, 6).toString();
        String AreaLaboral = Tbl_Empleados.getValueAt(fila, 7).toString();
        String FechaNacimiento = Tbl_Empleados.getValueAt(fila, 8).toString();
        String Sexo = Tbl_Empleados.getValueAt(fila, 9).toString();
        String Activo = Tbl_Empleados.getValueAt(fila, 10).toString();
        
        

        Txt_IdEmpleado.setText(Id);
        Txt_NombreEmpleado.setText(Nombre);
        Txt_ApellidoEmpleado.setText(Apellido);
        Txt_TelefonoEmpleado.setText(Telefono);
        Txt_CorreoEmpleado.setText(Correo);
        jComboBox1.setSelectedItem(TipoDocumento);
        Txt_DocumentoEmpleado.setText(Documento);
        Txt_FechaNacimiento.setText(FechaNacimiento);
        jComboBox2.setSelectedItem(Sexo);
        jComboBox3.setSelectedItem(AreaLaboral);
        Txt_Activo.setText(Activo);
        
        if(Activo == "Activado"){
        Btn_Activar_Desactivar.setText("Desactivar");
        }else{
        
             Btn_Activar_Desactivar.setText("Activar");
        
        }
        }
        }
        
    }//GEN-LAST:event_Tbl_EmpleadosMouseClicked

    private void Btn_Activar_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Activar_DesactivarActionPerformed
         
        int fila = Tbl_Empleados.getSelectedRow();

        if(fila != -1){

            try{
            Activar_Desactivar();
             } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al desactivar: " + ex);
          
        }

        }else{

            JOptionPane.showMessageDialog(this, "Debe seleccionar el elemento a Activar o Desactivar en la Fila");

        }   
        
    }//GEN-LAST:event_Btn_Activar_DesactivarActionPerformed

    private void Btn_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AñadirActionPerformed

        try{
        LlenarEmpleado();
        } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al añadir: " + ex);
          
        }
        
    }//GEN-LAST:event_Btn_AñadirActionPerformed

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
         
        int fila = Tbl_Empleados.getSelectedRow();
        if(fila == -1){

            JOptionPane.showMessageDialog(this, "Debe seleccionar el elemento a actualizar en la Fila");

        }else{

            try{
            EditarEmpleado();
            LimpiarEmpleados();
            } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al editar: " + ex);
          
        }
        } 
        
          
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void Txt_ApellidoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ApellidoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ApellidoEmpleadoActionPerformed

    private void Txt_ApellidoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ApellidoEmpleadoKeyTyped
       
        
        char c = evt.getKeyChar();
        String Texto = Txt_ApellidoEmpleado.getText();

        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')){

            if(c == 'á' || c == 'é' || c == 'í' || c == 'ó' || c == 'ú'){
            }
            else{
            evt.consume();
            }
            
        }
        
        if (Txt_ApellidoEmpleado.getText().length() >= 20){
        
        evt.consume();
        
        }
    
         if((evt.getKeyChar() == 22)){
        
            Txt_ApellidoEmpleado.setText(Texto.substring(0, 20));
                    
        }
          
        if (Txt_ApellidoEmpleado.getText().length() == 1){

            char mayuscula = Texto.charAt(0);
            Texto = Character.toUpperCase(mayuscula)+ Texto.substring(1,Texto.length());
            Txt_ApellidoEmpleado.setText(Texto);

        }
        
    }//GEN-LAST:event_Txt_ApellidoEmpleadoKeyTyped

    private void Txt_TelefonoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TelefonoEmpleadoKeyTyped
         
        char c = evt.getKeyChar();
        String Texto = Txt_TelefonoEmpleado.getText();
       
        if(c < '0' || c > '9') {
        
            //consume no valida los datos
            evt.consume();
                     
        }
        
        if (Txt_TelefonoEmpleado.getText().length() == 0 && (c == '0' || c == '4' || c == '5' || c == '6' || c == '1') ){
       
        evt.consume();
        JOptionPane.showMessageDialog(this, "El número de teléfono debe de comenzar con 2, 3, 7, 8 ó 9","Error",JOptionPane.ERROR_MESSAGE);
        
        }
        
        
        if (Txt_TelefonoEmpleado.getText().length() >= 8){
        
        evt.consume();
        
        }
        
        if((evt.getKeyChar() == 22)){
        
            Txt_TelefonoEmpleado.setText(Texto.substring(0, 8));
                    
        }
        
    }//GEN-LAST:event_Txt_TelefonoEmpleadoKeyTyped

    private void Txt_NombreEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreEmpleadoKeyReleased
         
        
        
    }//GEN-LAST:event_Txt_NombreEmpleadoKeyReleased

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

        try{
            
        ActualizarEmpleados2(Txt_NombreEmpleado.getText());
        
        }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al buscar: " + ex);
          
        }
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void Txt_FechaNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_FechaNacimientoKeyTyped
         
        char c = evt.getKeyChar();
        String Texto = Txt_FechaNacimiento.getText();
        
        if(c < '0' || c > '9') {

            if(c == 47){
            }
            else{
            evt.consume();
            }
             
        }
        
        if (Txt_FechaNacimiento.getText().length() >= 10){
        
        evt.consume();
        
        }
        
        if((evt.getKeyChar() == 22)){
        
        Txt_FechaNacimiento.setText(Texto.substring(0, 10));
                    
        } 
        
    }//GEN-LAST:event_Txt_FechaNacimientoKeyTyped

    private void Txt_CorreoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_CorreoEmpleadoKeyTyped
   
        
        char c = evt.getKeyChar();
        String Texto = Txt_CorreoEmpleado.getText();
        
          if (Txt_CorreoEmpleado.getText().length() >= 45){
        
        evt.consume();
        
        }
        
        if((evt.getKeyChar() == 22)){
        
            Txt_CorreoEmpleado.setText(Texto.substring(0, 45));
                    
        }   
        
        
    }//GEN-LAST:event_Txt_CorreoEmpleadoKeyTyped

    private void Txt_DocumentoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DocumentoEmpleadoKeyTyped
       
        char c = evt.getKeyChar();
        String Texto = Txt_DocumentoEmpleado.getText();
        
         if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')&&(c < '0' || c > '9')){
        
            evt.consume();
        
        }
        
          if (Txt_DocumentoEmpleado.getText().length() >= 20){
        
            evt.consume();
        
        }
        
        if((evt.getKeyChar() == 22)){
        
            Txt_DocumentoEmpleado.setText(Texto.substring(0, 20));
                    
        }
        
    }//GEN-LAST:event_Txt_DocumentoEmpleadoKeyTyped

    private void BuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarApellidoActionPerformed

        try{
        
            ActualizarEmpleados3(Txt_ApellidoEmpleado.getText());
        
        }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al buscar: " + ex);
          
        }
        
    }//GEN-LAST:event_BuscarApellidoActionPerformed

    private void Btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReporteActionPerformed

        try{
        GenerarReporte();
        }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al imprimir reporte: " + ex);
          
        }
        
    }//GEN-LAST:event_Btn_ReporteActionPerformed

     
    
    
    
    
    
    
    private void ActualizarEmpleados(){
       
            DefaultTableModel t = new DefaultTableModel();
            Tbl_Empleados.setModel(t);
            t.addColumn("Id");
            t.addColumn("Nombre");
            t.addColumn("Apellido");
            t.addColumn("Telefono");
            t.addColumn("Correo");
            t.addColumn("Tipo Documento");
            t.addColumn("Documento");
            t.addColumn("Area Laboral");
            t.addColumn("Fecha de nacimiento");
            t.addColumn("Sexo");
            t.addColumn("Estado");
        
            List<Empleados> empleados = this.daoEmpleado.findEmpleadosEntities();
        
            String s;
            for(Empleados Empleados : empleados){
                
                if(Empleados.isActivoEmpleado() == true){
                s = "Activado";
                }else{
                s = "Desactivado";
                }
                t.addRow(
                    new Object[]{
                        Empleados.getIdEmpleados(),
                        Empleados.getNombreEmpleado(),
                        Empleados.getApellidoEmpleado(),
                        Empleados.getTelefonoEmpleado(),
                        Empleados.getCorreoEmpleado(),
                        GetNombreTipoDocumento(Empleados.getIdTipoDocumento()),
                        Empleados.getDocumento(),
                        GetNombreAreaLaboral(Empleados.getIdAreaLaboral()),
                        MostrarFecha(Empleados.getFechaDeNacimiento().toString()),
                        GetNombreSexo(Empleados.getIdSexo()),
                        s
                    });
            }
       
       
       }
    
    
     private void Activar_Desactivar(){
        
        int fila = Tbl_Empleados.getSelectedRow();
        
        String a = Txt_Activo.getText().toString();
       
        
        if(Txt_IdEmpleado.getText().equals("6")){
        
        JOptionPane.showMessageDialog(this, "El Admin no puede ser Desactivado","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(a.equals("Activado")){
        
            
            objEmpleado.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));
            objEmpleado.setNombreEmpleado(Tbl_Empleados.getValueAt(fila, 1).toString());
            objEmpleado.setApellidoEmpleado(Tbl_Empleados.getValueAt(fila, 2).toString());
            objEmpleado.setTelefonoEmpleado(Integer.parseInt(Tbl_Empleados.getValueAt(fila, 3).toString()));
            objEmpleado.setCorreoEmpleado(Tbl_Empleados.getValueAt(fila, 4).toString());
            objEmpleado.setIdTipoDocumento(GetIdTipoDocumento(Tbl_Empleados.getValueAt(fila, 5).toString()));
            objEmpleado.setDocumento(Tbl_Empleados.getValueAt(fila, 6).toString());
            objEmpleado.setIdAreaLaboral(GetIdAreaLaboral(Tbl_Empleados.getValueAt(fila, 7).toString()));
            objEmpleado.setFechaDeNacimiento(Timestamp.valueOf(GuardarFecha(Tbl_Empleados.getValueAt(fila, 8).toString())+ " 00:00:00"));
            objEmpleado.setIdSexo(GetIdSexo(Tbl_Empleados.getValueAt(fila, 9).toString()));
            objEmpleado.setActivoEmpleado(false);
            

        
        try {
            daoEmpleado.edit(objEmpleado);
            ActualizarEmpleados();
            Btn_Activar_Desactivar.setText("Activar");
            JOptionPane.showMessageDialog(this, "Se desactivó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al desactivar: " + ex);
          
        }
        
        
        LimpiarEmpleados(); 
        
        }else{
        
            objEmpleado.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));
            objEmpleado.setNombreEmpleado(Tbl_Empleados.getValueAt(fila, 1).toString());
            objEmpleado.setApellidoEmpleado(Tbl_Empleados.getValueAt(fila, 2).toString());
            objEmpleado.setTelefonoEmpleado(Integer.parseInt(Tbl_Empleados.getValueAt(fila, 3).toString()));
            objEmpleado.setCorreoEmpleado(Tbl_Empleados.getValueAt(fila, 4).toString());
            objEmpleado.setIdTipoDocumento(GetIdTipoDocumento(Tbl_Empleados.getValueAt(fila, 5).toString()));
            objEmpleado.setDocumento(Tbl_Empleados.getValueAt(fila, 6).toString());
            objEmpleado.setIdAreaLaboral(GetIdAreaLaboral(Tbl_Empleados.getValueAt(fila, 7).toString()));
            objEmpleado.setFechaDeNacimiento(Timestamp.valueOf(GuardarFecha(Tbl_Empleados.getValueAt(fila, 8).toString())+ " 00:00:00"));
            objEmpleado.setIdSexo(GetIdSexo(Tbl_Empleados.getValueAt(fila, 9).toString()));
            objEmpleado.setActivoEmpleado(true);
        
        try {
            daoEmpleado.edit(objEmpleado);
            ActualizarEmpleados();
            Btn_Activar_Desactivar.setText("Desactivar");
            JOptionPane.showMessageDialog(this, "Se activó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al activar: " + ex);
          
        }
        
        LimpiarEmpleados();
        
        }
        
        }
    
     
     
     private void LlenarEmpleado(){
        
        if(Txt_NombreEmpleado.getText().length() < 3){
        
        JOptionPane.showMessageDialog(this, "El nombre del empleado tiene que contener al menos 3 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_NombreEmpleado.getText())== true){
        
        JOptionPane.showMessageDialog(this, "El nombre del Empleado no puede contener 3 letras seguidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_ApellidoEmpleado.getText().length() < 2){
        
        JOptionPane.showMessageDialog(this, "El apellido del empleado tiene que contener al menos 2 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_ApellidoEmpleado.getText())== true){
        
        JOptionPane.showMessageDialog(this, "El apellido del Empleado no puede contener 3 letras seguidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_TelefonoEmpleado.getText().length() < 8){
        
        JOptionPane.showMessageDialog(this, "El Teléfono debe de contener de 8 a 10 números","Error",JOptionPane.ERROR_MESSAGE);     
        
        }else if(ValidacionMail(Txt_CorreoEmpleado.getText())== false){
        
        JOptionPane.showMessageDialog(this, "Formato de E-mail inválido, el formato es: nombredeusuario@nombrededominio.extensión","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox1.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar un Tipo de documento","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if((String.valueOf(jComboBox1.getSelectedItem()).equalsIgnoreCase("dni") && ValidacionDNI(Txt_DocumentoEmpleado.getText()) == false ) || (String.valueOf(jComboBox1.getSelectedItem()).equalsIgnoreCase("identidad") && ValidacionDNI(Txt_DocumentoEmpleado.getText()) == false )){
        
        JOptionPane.showMessageDialog(this, "Formato de DNI inválido, el formato es: 0801199912080","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if((String.valueOf(jComboBox1.getSelectedItem()).equalsIgnoreCase("rtn") && ValidacionRTN(Txt_DocumentoEmpleado.getText())== false)){
        
        JOptionPane.showMessageDialog(this, "Formato de RTN inválido, el formato es: 08011999120801","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionFecha(Txt_FechaNacimiento.getText())== false || Txt_FechaNacimiento.getText().length() < 10 ){
        
        JOptionPane.showMessageDialog(this, "Formato de la fecha inválido, el formato es: DD/MM/YYYY","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Fechavalida(Txt_FechaNacimiento.getText()) == false){
        
        JOptionPane.showMessageDialog(this, "Formato de la fecha inválido, el formato es: DD/MM/YYYY","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox2.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar un sexo","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox3.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una Área Laboral","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionDocumento(Txt_DocumentoEmpleado.getText()) == true){
        
        JOptionPane.showMessageDialog(this, "Documento ya ha sido registrado con otro Empleado","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_DocumentoEmpleado.getText().length() < 6){
        
        JOptionPane.showMessageDialog(this, "El documento debe de contener al menos 6 caracteres","Error",JOptionPane.ERROR_MESSAGE);
        
        }else{
            objEmpleado.setIdEmpleados(IdEmpleado());
            objEmpleado.setNombreEmpleado(Txt_NombreEmpleado.getText());
            objEmpleado.setApellidoEmpleado(Txt_ApellidoEmpleado.getText());
            objEmpleado.setTelefonoEmpleado(Long.parseLong(Txt_TelefonoEmpleado.getText()));
            objEmpleado.setCorreoEmpleado(Txt_CorreoEmpleado.getText());
            objEmpleado.setIdTipoDocumento(GetIdTipoDocumento(String.valueOf(jComboBox1.getSelectedItem())));
            objEmpleado.setDocumento(Txt_DocumentoEmpleado.getText());
            objEmpleado.setFechaDeNacimiento(Timestamp.valueOf(GuardarFecha(Txt_FechaNacimiento.getText())+ " 00:00:00"));
            objEmpleado.setIdSexo(GetIdSexo(String.valueOf(jComboBox2.getSelectedItem())));
            objEmpleado.setIdAreaLaboral(GetIdAreaLaboral(String.valueOf(jComboBox3.getSelectedItem())));
            objEmpleado.setActivoEmpleado(true);
                       
            
        try {
            daoEmpleado.create(objEmpleado);
            ActualizarEmpleados();
            LimpiarEmpleados();
            JOptionPane.showMessageDialog(this, "Se guardó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al añadir: " + ex);
          
        }
       }   
       } 
     
     
     private void EditarEmpleado(){
            
            
        if(Txt_NombreEmpleado.getText().length() < 3){
        
        JOptionPane.showMessageDialog(this, "El nombre del empleado tiene que contener al menos 3 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_IdEmpleado.getText().equals("6")){
        
        JOptionPane.showMessageDialog(this, "El Admin no puede ser editado","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_NombreEmpleado.getText())== true){
        
        JOptionPane.showMessageDialog(this, "El nombre del Empleado no puede contener 3 letras seguidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_ApellidoEmpleado.getText().length() < 2){
        
        JOptionPane.showMessageDialog(this, "El apellido del empleado tiene que contener al menos 2 letras","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionTresLetras(Txt_ApellidoEmpleado.getText())== true){
        
        JOptionPane.showMessageDialog(this, "El apellido del Empleado no puede contener 3 letras seguidas","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_TelefonoEmpleado.getText().length() < 8){
        
        JOptionPane.showMessageDialog(this, "El Teléfono debe de contener de 8 a 10 números","Error",JOptionPane.ERROR_MESSAGE);     
        
        }else if(ValidacionMail(Txt_CorreoEmpleado.getText())== false){
        
        JOptionPane.showMessageDialog(this, "Formato de E-mail inválido, el formato es: nombredeusuario@nombrededominio.extensión","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox1.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar un Tipo de documento","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if((String.valueOf(jComboBox1.getSelectedItem()).equalsIgnoreCase("dni") && ValidacionDNI(Txt_DocumentoEmpleado.getText()) == false ) || (String.valueOf(jComboBox1.getSelectedItem()).equalsIgnoreCase("identidad") && ValidacionDNI(Txt_DocumentoEmpleado.getText()) == false )){
        
        JOptionPane.showMessageDialog(this, "Formato de DNI inválido, el formato es: 0801199912080","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if((String.valueOf(jComboBox1.getSelectedItem()).equalsIgnoreCase("rtn") && ValidacionRTN(Txt_DocumentoEmpleado.getText())== false)){
        
        JOptionPane.showMessageDialog(this, "Formato de RTN inválido, el formato es: 08011999120801","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(ValidacionFecha(Txt_FechaNacimiento.getText())== false || Txt_FechaNacimiento.getText().length() < 10){
        
        JOptionPane.showMessageDialog(this, "Formato de la fecha inválido, el formato es: DD/MM/YYYY","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Fechavalida(Txt_FechaNacimiento.getText()) == false){
        
        JOptionPane.showMessageDialog(this, "Formato de la fecha inválido, el formato es: DD/MM/YYYY","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox2.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar un sexo","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(String.valueOf(jComboBox3.getSelectedItem()) == "Seleccione"){
        
        JOptionPane.showMessageDialog(this, "Debe de seleccionar una Área Laboral","Error",JOptionPane.ERROR_MESSAGE);
        
        }else if(Txt_DocumentoEmpleado.getText().length() < 6){
        
        JOptionPane.showMessageDialog(this, "El documento debe de contener al menos 6 caracteres","Error",JOptionPane.ERROR_MESSAGE);
        
        }else{
                
            objEmpleado.setIdEmpleados(Integer.parseInt(Txt_IdEmpleado.getText()));
            objEmpleado.setNombreEmpleado(Txt_NombreEmpleado.getText());
            objEmpleado.setApellidoEmpleado(Txt_ApellidoEmpleado.getText());
            objEmpleado.setTelefonoEmpleado(Long.parseLong(Txt_TelefonoEmpleado.getText()));
            objEmpleado.setCorreoEmpleado(Txt_CorreoEmpleado.getText());
            objEmpleado.setIdTipoDocumento(GetIdTipoDocumento(String.valueOf(jComboBox1.getSelectedItem())));
            objEmpleado.setDocumento(Txt_DocumentoEmpleado.getText());
            objEmpleado.setFechaDeNacimiento(Timestamp.valueOf(GuardarFecha(Txt_FechaNacimiento.getText())+ " 00:00:00"));
            objEmpleado.setIdSexo(GetIdSexo(String.valueOf(jComboBox2.getSelectedItem())));
            objEmpleado.setIdAreaLaboral(GetIdAreaLaboral(String.valueOf(jComboBox3.getSelectedItem())));
            
                   
            String a = Txt_Activo.getText().toString();
            if(a.equals("Activado")){
            objEmpleado.setActivoEmpleado(true);
            }else{
            objEmpleado.setActivoEmpleado(false);
            }
            
        try {
            daoEmpleado.edit(objEmpleado);
            ActualizarEmpleados();
             JOptionPane.showMessageDialog(this, "Se actualizó correctamente");
        } catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al editar: " + ex);
          
        }
       }  
            
            }
            
     public static boolean Fechavalida(String date){
        try {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            df.setLenient(false);
            df.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }}
     
     
       private void LimpiarEmpleados(){
        
        try{
        
        if(ValidarAgregar(N.id) == true){
        Btn_Añadir.setEnabled(true);
        }
        Btn_Editar.setEnabled(false);
        Btn_Activar_Desactivar.setEnabled(false);
        Txt_IdEmpleado.setText("");
        Txt_NombreEmpleado.setText("");
        Txt_ApellidoEmpleado.setText("");
        Txt_TelefonoEmpleado.setText("");
        Txt_CorreoEmpleado.setText("");
        jComboBox1.setSelectedIndex(0);
        Txt_DocumentoEmpleado.setText("");
        Txt_FechaNacimiento.setText("");
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        
        }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al limpiar: " + ex);
          
        }
        
        
       }
    
    
       
       public static int IdEmpleado(){
        
             EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
             EntityManager em = emf.createEntityManager();
      
             String select = "SELECT Max(idEmpleados)+1 FROM Empleados";
   
             Query query = em.createQuery(select);
             
             if(query.getSingleResult() == null){
             
             return 1;
             
             }else{
                 
             return Integer.parseInt(query.getSingleResult().toString());
             
             }
        }
       
       
    public void listaTipoDocumento(){
  
      jComboBox1.removeAllItems();
  
      List<TipoDocumento> tipoDocumento = this.daoTipoDocumento.findTipoDocumentoEntities();
  
             jComboBox1.addItem("Seleccione");
      
         for(TipoDocumento TipoDocumento : tipoDocumento){
             
             if(TipoDocumento.isActivoTipoDocumento() == true){
             String lista = TipoDocumento.getNombreTipoDocumento();
             jComboBox1.addItem(lista);
             
             }
                                
                    };
  }
    
    public void listaSexo(){
  
         jComboBox2.removeAllItems();
  
         List<Sexo> sexo = this.daoSexo.findSexoEntities();
  
         jComboBox2.addItem("Seleccione");
      
         for(Sexo Sexo : sexo){
             
             String lista = Sexo.getNombreSexo();
             jComboBox2.addItem(lista);
                                
                    }
  } 
    
    public void listaAreaLaboral(){
  
      jComboBox3.removeAllItems();
  
      List<AreaLaboral> areaLaboral = this.daoAreaLaboral.findAreaLaboralEntities();
  
             jComboBox3.addItem("Seleccione");
      
         for(AreaLaboral AreaLaboral : areaLaboral){
             
             if(AreaLaboral.isActivoAreaLaboral() == true){
             String lista = AreaLaboral.getNombreAreaLaboral();
             jComboBox3.addItem(lista);
             
             }
                                
                    };
  }
    
    public static boolean ValidacionFecha(String Nombre){
        
    return Nombre.matches("^(?:3[01]|[12][0-9]|0?[1-9])([\\/])(0?[0-9]|1[0-2])\\1\\d{4}$");
        
        }
    
    public static boolean ValidacionDias(String Fecha){
        
        //  21/03/1999
        int Año = Integer.parseInt(Fecha.substring(6, 10));
        Fecha = Fecha.substring(0, 5);
         
        System.out.println(Año);
        
        if ((Año % 4 == 0) && ((Año % 100 != 0) || (Año % 400 == 0))){
            
	if(Fecha.equals("30/02") || Fecha.equals("31/02") || Fecha.equals("31/04") || Fecha.equals("31/06") || Fecha.equals("31/09") ||
           Fecha.equals("31/11")|| Fecha.equals("29/02")){
      
            return true;
        
        }else{
        
            return false;
           
        }
       
        }else{
	
           if(Fecha.equals("30/02") || Fecha.equals("31/02") || Fecha.equals("31/04") || Fecha.equals("31/06") || Fecha.equals("31/09") ||
           Fecha.equals("31/11")){
      
            return true;
        
        }else{
        
            return false;
           
        }   }   }
    
    
     public static boolean ValidacionDNI(String DNI){
        
        return DNI.matches("^[0-1]{1}[0-9]{12}$");
                
        }
       
       public static boolean ValidacionRTN(String RTN){
        
        return RTN.matches("^[0-1]{1}[0-9]{13}$");
                
        }
    
     private static boolean ValidacionTresLetras(String cadena){
        
          String patron = "^\\b(\\w*)(\\w)\\2{2,}(\\w*)\\b";
        Pattern patt = Pattern.compile(patron);
        Matcher comparador = patt.matcher(cadena);
        if(comparador.matches()){
            return true;
        }else
        {
            return false;
        }
              
        } 
     
     public static boolean ValidacionMail(String Nombre){
        
          return Nombre.matches("[^@]+@[^@]+[a-zA-Z]{1,}\\.[a-zA-Z]{2,}");    
        
        }
    
    public static String GuardarFecha(String f){
        
        
        //  21/03/1999
         
        String dia = f.substring(0, 2);
        String mes = f.substring(3, 5);
        String año = f.substring(6, 10);
        
        return año+"-"+mes+"-"+dia;
        
    
    }
    
    public static String MostrarFecha(String f){
        
         
        String dia = f.substring(0, 4);
        String mes = f.substring(5, 7);
        String año = f.substring(8, 10);
        
        return año+"/"+mes+"/"+dia;
        
    
    }
    
    private static String GetNombreTipoDocumento(int id){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT nombreTipoDocumento FROM TipoDocumento WHERE idTipoDocumento = '"+ id+ "'";
              Query query = em.createQuery(select);
    
              return query.getSingleResult().toString() ;
            
          }         
   
          private static int GetIdTipoDocumento(String Nombre){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT idTipoDocumento FROM TipoDocumento WHERE nombreTipoDocumento = '"+ Nombre+ "'";
              Query query = em.createQuery(select);
    
              return Integer.parseInt(query.getSingleResult().toString());
            
          }   
          
          
          private static String GetNombreSexo(int id){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT nombreSexo FROM Sexo WHERE idSexo = '"+ id+ "'";
              Query query = em.createQuery(select);
    
              return query.getSingleResult().toString() ;
            
          }   
          
          private static int GetIdSexo(String Nombre){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT idSexo FROM Sexo WHERE nombreSexo  = '"+ Nombre + "'";
              Query query = em.createQuery(select);
    
              return Integer.parseInt(query.getSingleResult().toString());
            
          } 
    
          
          private static String GetNombreAreaLaboral(int id){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT nombreAreaLaboral FROM AreaLaboral WHERE idAreaLaboral = '"+ id+ "'";
              Query query = em.createQuery(select);
    
              return query.getSingleResult().toString() ;
            
          }         
   
          private static int GetIdAreaLaboral(String Nombre){
        
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
              EntityManager em = emf.createEntityManager();
              String select = "SELECT idAreaLaboral FROM AreaLaboral WHERE nombreAreaLaboral = '"+ Nombre+ "'";
              Query query = em.createQuery(select);
    
              return Integer.parseInt(query.getSingleResult().toString());
            
          }   
    
          
       private void ActualizarEmpleados2(String Nombres){
       
       DefaultTableModel t = new DefaultTableModel();
            Tbl_Empleados.setModel(t);
            t.addColumn("Id");
            t.addColumn("Nombre");
            t.addColumn("Apellido");
            t.addColumn("Telefono");
            t.addColumn("Correo");
            t.addColumn("Tipo Documento");
            t.addColumn("Documento");
            t.addColumn("Area Laboral");
            t.addColumn("Fecha de nacimiento");
            t.addColumn("Sexo");
            t.addColumn("Estado");
        
            List<Empleados> empleados = buscarPersonas(Nombres);
        
            String s;
            for(Empleados Empleados : empleados){
                
                if(Empleados.isActivoEmpleado() == true){
                s = "Activado";
                }else{
                s = "Desactivado";
                }
                t.addRow(
                    new Object[]{
                        Empleados.getIdEmpleados(),
                        Empleados.getNombreEmpleado(),
                        Empleados.getApellidoEmpleado(),
                        Empleados.getTelefonoEmpleado(),
                        Empleados.getCorreoEmpleado(),
                        GetNombreTipoDocumento(Empleados.getIdTipoDocumento()),
                        Empleados.getDocumento(),
                        GetNombreAreaLaboral(Empleados.getIdAreaLaboral()),
                        MostrarFecha(Empleados.getFechaDeNacimiento().toString()),
                        GetNombreSexo(Empleados.getIdSexo()),
                        s
                    });
            }
       
       
       
             
       }
       
       public List<Empleados> buscarPersonas(String Nombres){
       
           Empleados c;
             
           EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
           EntityManager em = emf.createEntityManager();
           String select = "SELECT e From Empleados e WHERE e.nombreEmpleado LIKE'"+ Nombres + "%'";
           Query query = em.createQuery(select);
           List<Empleados> lista = query.getResultList();
           return lista;
           
       }
       
        private void ActualizarEmpleados3(String Nombres){
       
       DefaultTableModel t = new DefaultTableModel();
            Tbl_Empleados.setModel(t);
            t.addColumn("Id");
            t.addColumn("Nombre");
            t.addColumn("Apellido");
            t.addColumn("Telefono");
            t.addColumn("Correo");
            t.addColumn("Tipo Documento");
            t.addColumn("Documento");
            t.addColumn("Area Laboral");
            t.addColumn("Fecha de nacimiento");
            t.addColumn("Sexo");
            t.addColumn("Estado");
        
            List<Empleados> empleados = buscarApellido(Nombres);
        
            String s;
            for(Empleados Empleados : empleados){
                
                if(Empleados.isActivoEmpleado() == true){
                s = "Activado";
                }else{
                s = "Desactivado";
                }
                t.addRow(
                    new Object[]{
                        Empleados.getIdEmpleados(),
                        Empleados.getNombreEmpleado(),
                        Empleados.getApellidoEmpleado(),
                        Empleados.getTelefonoEmpleado(),
                        Empleados.getCorreoEmpleado(),
                        GetNombreTipoDocumento(Empleados.getIdTipoDocumento()),
                        Empleados.getDocumento(),
                        GetNombreAreaLaboral(Empleados.getIdAreaLaboral()),
                        MostrarFecha(Empleados.getFechaDeNacimiento().toString()),
                        GetNombreSexo(Empleados.getIdSexo()),
                        s
                    });
            }
       
       
       
             
       }
       
       public List<Empleados> buscarApellido(String Nombres){
       
           Empleados c;
             
           EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
           EntityManager em = emf.createEntityManager();
           String select = "SELECT e From Empleados e WHERE e.apellidoEmpleado LIKE'"+ Nombres + "%'";
           Query query = em.createQuery(select);
           List<Empleados> lista = query.getResultList();
           return lista;
           
       }
          
          public static boolean ValidacionDocumento(String Documento){
       
         EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
         EntityManager em = emf.createEntityManager();
      
             String select = "SELECT idEmpleados FROM Empleados WHERE documento  = '"+Documento+ "'";
   
             Query query = em.createQuery(select);
       
             if(query.getResultList().size() == 0){
             
             return false;
             
             }else{
             
             return true;
                
             }
             
        }
          
          private void GenerarReporte(){
       
        
             Connection con;
             
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            
        try{
        
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Microcosmos?zeroDateTimeBehavior=convertToNull", "root", "12345");
        
        JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/ReporteEmpleados.jasper"));
        
        Map parametros = new HashMap<String, Object>();
        
        parametros.put("Empleado", N.getNombre());
   
        JasperPrint jprint = JasperFillManager.fillReport(report,parametros, con );
        JasperViewer view = new JasperViewer(jprint,false);
        view.setTitle("Reporte Articulos");
        Image icon = new ImageIcon(getClass().getResource("/imagenes/IconoMicrocosmos.png")).getImage();
        view.setIconImage(icon);
        

        final JRViewer viewer = new JRViewer(jprint);
            JRSaveContributor[] contrbs = viewer.getSaveContributors();

            for (JRSaveContributor saveContributor : contrbs)
            {
                if (!(saveContributor instanceof net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor
                    || saveContributor instanceof net.sf.jasperreports.view.save.JRPdfSaveContributor))
            viewer.removeSaveContributor(saveContributor);
        }
        view.setContentPane(viewer);
        view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        view.setVisible(true);
        

        view.show();

      
    }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al imprimir reporte: " + ex);
          
        }
        }catch(Exception ex){
        
        log.Logs("PantallaEmpleados", "Error al imprimir reporte: " + ex);
          
        }
                
          }
          
         
          
    public void RestringirPermisos(boolean Agregar,boolean Editar,boolean Desactivar,boolean Imprimir,boolean buscar){
        
      
      if(Agregar == false){
       
        Btn_Añadir.setEnabled(false);
          
    }
      if(Editar == false){
          
        Btn_Editar.setEnabled(false);
                
    }
      if(Desactivar == false){

        Btn_Activar_Desactivar.setEnabled(false);
                
    }
      if(Imprimir == false){
          
        Btn_Reporte.setEnabled(false);
                
    }
      if(buscar == false){
          
        BuscarApellido.setEnabled(false);
        Buscar.setEnabled(false);
                
    }
     
    }
          
          
    public boolean ValidarAgregar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where agregarEmpleados = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
          
    public boolean ValidarEditar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where editarEmpleados = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
    
    public boolean ValidarDesactivar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where desactivarEmpleados = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
    
    public boolean ValidarImprimir(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where imprimirEmpleados = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
    
    public boolean ValidarBuscar(int id){
        
        
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("DB");
    EntityManager em = emf.createEntityManager();

    
    String select = "SELECT idPermisos FROM Permisos Where buscarEmpleados = true AND idUsuario IN (SELECT idUsuario FROM Usuarios WHERE idEmpleados = '"+ id+ "')";

    Query query = em.createQuery(select);
      
      if(query.getResultList().size() == 0){
       
          return false;
          
    }else{
        
          return true;
        
    }
     
    }
          
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Activar_Desactivar;
    private javax.swing.JButton Btn_Añadir;
    private javax.swing.JButton Btn_Editar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Regresar;
    private javax.swing.JButton Btn_Reporte;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton BuscarApellido;
    private javax.swing.JTable Tbl_Empleados;
    private javax.swing.JTextField Txt_Activo;
    private javax.swing.JTextField Txt_ApellidoEmpleado;
    private javax.swing.JTextField Txt_CorreoEmpleado;
    private javax.swing.JTextField Txt_DocumentoEmpleado;
    private javax.swing.JTextField Txt_FechaNacimiento;
    private javax.swing.JTextField Txt_IdEmpleado;
    private javax.swing.JTextField Txt_NombreEmpleado;
    private javax.swing.JTextField Txt_TelefonoEmpleado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
